### ISSUE TITLE
Colored points do not appear in plot

### ISSUE THREAD

**Issue by paulandroide** [RitchieLab/eQTpLot#11]
Hi! First of all, thanks for the package.

I've trying to use it to see SNCA gen in Substantia nigra tissue, and actually I only need plot 1 and 2. However, despite it runs alright, my plot does not have any color, just gray squares. I thought it could be because I didn't supply LD data, but I think that's not it.

The only warning I get back is Removed 162 rows containing missing values (geom_point).
Could be this the reason?
I apologize in advance since I'm a new R user. 

Thanks!
![SNCA PD Substantia_nigra WithoutCongruenceData WithoutLinkageData eQTpLot](https://user-images.githubusercontent.com/78987720/134556770-833f5013-0dce-49a4-a977-8ebb1296eeda.png)

**Comment by anastasia-lucas** [comment]
Hi @paulandroide,

Thanks for using the package. I will take a look into this issue as soon as I am able, but it may speed up things if you are able to provide the exact code you ran that generated this plot, so I can take a look on my end.

**Comment by paulandroide** [comment]
Sure thing!

##load necessary packages
require(data.table)
library(data.table)  
library(dplyr)
library(dbplyr)
library(devtools)
library(tidyr)
library(eQTpLot)
library(BiocManager)
library(ggplot2)
library(stringi)
library(eQTpLot)
library(ggnewscale)
library(patchwork)
library(Gviz)
library(GenomicRanges)
library(biomaRt)
library(ggpubr)
library(LDheatmap)
library(ggplotify)

require(data.table)
setwd("C:/users/paula/Desktop/eQTpLot-master/data/")
gwas_df <- fread('META_no23_yesUKBB_chr4_SNCA_region_forPlot2.txt')
eqtl_df <- fread('eQTL_SNCA_for_plot.txt')
head(gwas_df)
head(eqtl_df)
eqtl_df$Gene.Symbol <- sub("ENSG00000145335", "SNCA", eqtl_df$Gene.Symbol)
eQTpLot(GWAS.df = gwas_df, eQTL.df = eqtl_df, gene="SNCA", sigpvalue_eQTL=0.05, gbuild = "hg19",  trait = "PD", tissue =  "Substantia_nigra", CollapseMethod = "min", ylima = 15 ) 

Also the files if needed.


Thanks very much!
[eQTL_SNCA_for_plot.txt](https://github.com/RitchieLab/eQTpLot/files/7220577/eQTL_SNCA_for_plot.txt)
[META_no23_yesUKBB_chr4_SNCA_region_forPlot2.txt](https://github.com/RitchieLab/eQTpLot/files/7220578/META_no23_yesUKBB_chr4_SNCA_region_forPlot2.txt)
o

**Comment by anastasia-lucas** [comment]
Thanks, this is very helpful. I am a bit backlogged at the moment, but I will try to get back to you soon.

**Comment by paulandroide** [comment]
Thanks, don't worry, I really appreciate you taking the time. Best regards!

**Comment by TGDrivas** [comment]
Hi @paulandroide,

I think the issue here is that your eQTL data does not contain any variants within the window that you are looking at. If I extend the window using the "range" argument as follows:

eQTpLot(GWAS.df = gwas_df, eQTL.df = eqtl_df, gene="SNCA", sigpvalue_eQTL=0.05, gbuild = "hg19", trait = "PD", tissue = "Substantia_nigra", CollapseMethod = "min", ylima = 15, range = 1000)

I can see that there are a few variants showing up in the plot now at about 91.2 mb:

<img width="928" alt="Screen Shot 2021-09-29 at 12 39 47 PM" src="https://user-images.githubusercontent.com/89800277/135312113-7ecdbabd-f0e0-49d8-9bf2-98aabc7a0eb8.png">

In fact, looking at all the eQTL data in your file (combining across all tissues, and setting the significance threshold to 1) with the following command:

eQTpLot(GWAS.df = gwas_df, eQTL.df = eqtl_df, gene="SNCA", sigpvalue_eQTL=1, gbuild = "hg19", trait = "PD", tissue = "all", CollapseMethod = "min", ylima = 15, range = 1000)

We can see that really all of your eQTL data is for a region pretty far away from your gene of interest, and the GWAS peak you appear to be investigating:

<img width="1033" alt="Screen Shot 2021-09-29 at 12 43 13 PM" src="https://user-images.githubusercontent.com/89800277/135312671-844a19f4-0094-4677-a6e3-5c3136cd6125.png">

Perhaps go back to your source data for the eQTL file and see if there is data for more variants closer to your region of interest?
