### ISSUE TITLE
Workflow to prepare input data form eQTpLot

### ISSUE THREAD

**Issue by okendojo** [RitchieLab/eQTpLot#21]
Thanks for making this great tool. Could you share the workflow/scripts you used to prepare the different input data?

**Comment by TGDrivas** [comment]
Hello, I'm glad you're enjoying our tool! The workflows/scripts will entirely depend on the software you use to generate  your GWAS data, etc. We tried to provide very detailed descriptions of the requirements for input files so that individual users could adapt their data to fit the required format (see the "Input files" section of the readme file included in the GitHub repo). If you have any specific questions after reading this over please reach out. Thank you!
